---
code: 505
internalName: NestedTryViolation
title: Found nested `try` block
---

{% import "macros.html" as macros with context %}


Forbid nested ``try`` blocks.

Notice, we check all possible slots for ``try`` block:
1. the ``try`` block itself
2. all ``except`` cases
3. ``else`` case
4. and ``finally`` case

Reasoning:
    Nesting ``try`` blocks indicates
    that something really bad happens to your logic.
    Why does it require two separate exception handlers?
    It is a perfect case to refactor your code.

Solution:
    Collapse two exception handlers together.
    Or create a separate function that will handle this second nested case.

Example::

    # Wrong:
    try:
        try:
            ...
        except SomeException:
            ...
    except SomeOtherException:
        ...

    try:
        ...
    except SomeOtherException:
        try:
            ...
        except SomeException:
            ...

.. versionadded:: 0.8.0
.. versionchanged:: 0.11.0