---
code: 501
internalName: UselessFinallyViolation
title: Found `finally` in `try` block without `except`
---

{% import "macros.html" as macros with context %}


Forbid ``finally`` in ``try`` block without ``except`` block.

However, we allow to use ``try`` with just ``finally`` block
when function or method is decorated. Because we cannot control
what is going on in this decorator.
It might be ``@contextmanager`` or similar thing that requires this API.

Reasoning:
    This rule will reduce complexity and improve readability.

Solution:
    Refactor your ``try`` logic.
    Replace the ``try-finally`` statement with a ``with`` statement.

Example::

    # Correct:
    with open("filename") as f:
        f.write(...)

    # Wrong:
    try:
        f = open("filename")
        f.write(...)
    finally:
        f.close()

.. versionadded:: 0.3.0
.. versionchanged:: 0.11.0
.. versionchanged:: 0.14.0